# Generated by Django 4.0 on 2021-12-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipynuts', '0002_rename_data_fabricacao_produto_data_de_fabricação_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='peso_em_gramas',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preço',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
