# Generated by Django 4.0 on 2021-12-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipynuts', '0003_alter_produto_peso_em_gramas_alter_produto_preço'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='peso_em_gramas',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
