# Generated by Django 4.0 on 2021-12-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipynuts', '0004_alter_produto_peso_em_gramas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='peso_em_gramas',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preço',
            field=models.CharField(max_length=50),
        ),
    ]
