# Generated by Django 4.0 on 2021-12-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipynuts', '0006_alter_produto_data_de_fabricação_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
